### PR TITLE
Fix for elementCanBeScrolled failing if node is not an HTMLElement inside a shadow root

### LINKED ISSUE #108: "Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'." when placed inside a shadow root
Similar to #89, if the `<RemoveScroll>` component is used inside a shadow root, the code inside `elementCanBeScrolled` can sometimes fail with the error message: 
```
"Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'."
```

For example, when using `@radix-ui/react-dialog` (version `1.0.6-rc.5`), which uses `react-remove-scroll@2.5.7` (the error also occurs if you force `2.5.9`), if you attempt to scroll inside a shadow root when scrolling should be disabled (ie. if the content is not overflowing), then the error above is raised.

This could possibly be due to the shadow root not being an actual element. After some testing, it appears that this can be fixed by adding the following code to `elementCanBeScrolled()`:
```
if (!(node instanceof HTMLElement)) return false
```

### PR DESCRIPTION
**Pull request by PottyZA**
Fixes #108.

This PR adds a precautionary check to ensure that `node instanceof HTMLElement`, since it seems that it is possible that `node` might not be an Element. 

I would guess that `handleScroll`'s `event.target as any` can be more than just HTML elements in certain cases inside a Shadow root, so this guards against that.

### CODE REVIEW

File: src/handleScroll.ts [hunk 1]
```diff
@@ -1,10 +1,12 @@
-import { Axis } from './types';
+import {Axis} from './types';
 
 const alwaysContainsScroll = (node: HTMLElement): boolean =>
   // textarea will always _contain_ scroll inside self. It only can be hidden
   node.tagName === 'TEXTAREA';
 
 const elementCanBeScrolled = (node: HTMLElement, overflow: 'overflowX' | 'overflowY'): boolean => {
+  if (!(node instanceof HTMLElement)) return false;
```
Comment (theKashey) [inline src/handleScroll.ts:8]: 👍  simple and sound

Comment (maiconcarraro) [reply src/handleScroll.ts:8]: should it give a warning? in case someone passed the wrong variable, really hard to debug the situation w/o info (could be wrong)

Comment (theKashey) [reply src/handleScroll.ts:8]: this is internal-facing code, that _someone_ can be only the script itself.

Comment (PottyZA) [reply src/handleScroll.ts:8]: @theKashey Thanks for the comment! Feel free to merge if you're happy with the change. Otherwise, let me know if there are any tweaks you'd like me to make.
